- name: Hosts | populate registry domain address into hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ ansible_env['SSH_CLIENT'].split() | first }} {{ item.default_resolves }}"
    line: "{{ ansible_env['SSH_CLIENT'].split() | first }} {{ item.default_resolves }}"
    state: present
    backup: yes
    unsafe_writes: yes
  with_items: "{{ default_resolves }}"
  when: default_resolves is defined

- name: Hosts | populate registry domain address into hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.ip_address }} {{ item.domain_name }}"
    line: "{{ item.ip_address }} {{ item.domain_name }}"
    state: present
    backup: yes
    unsafe_writes: yes
  with_items: "{{ domain_resolves }}"
  when: domain_resolves is defined
