- name: enable hugepages with 1280 pages
  shell: echo 1280 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

- name: enable hugepages permanently
  shell: echo "vm.nr_hugepages = 1280" > /etc/sysctl.d/app-hugepage.conf

- name: enable iommu
  shell: echo GRUB_CMDLINE_LINUX_DEFAULT='$GRUB_CMDLINE_LINUX_DEFAULT intel_iommu=on' > /etc/default/grub.d/sriov_iommu.cfg

- name: update-grub
  shell: update-grub

- name: create sshd cgroup dir
  file:
    path: /etc/systemd/system/ssh.service.d
    state: directory

- name: copy sshd cgroup file
  copy:
    src: cgroup.conf
    dest: /etc/systemd/system/ssh.service.d

- name: systemd sshd daemon-reload
  ansible.builtin.systemd:
    daemon_reexec: true
