---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure directories to export exist
  file:  # noqa 208
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length
