apiVersion: v1
kind: Pod
metadata:
  name: kubespray
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "registry.kubespray.com"
  containers:
  - name: kubespray
    image: registry.cn-shenzhen.aliyuncs.com/cnmirror/kubernetes:v1.25.6-1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: REGISTRY_TYPE
      value: "registry"
    - name: REGISTRY_URL
      value: "https://registry.kubespray.com:5000"
    - name: REGISTRY_USERNAME
      value: "admin"
    - name: REGISTRY_PASSWORD
      value: "Registry12345"
    - name: MINIO_URL
      value: "http://registry.kubespray.com:9000"
    - name: MINIO_ROOT_USER
      value: "minioadmin"
    - name: MINIO_ROOT_PASSWORD
      value: "minioadmin"
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
      - mountPath: "/kubespray"
        name: kubespray-data
      - mountPath: "/etc/containers"
        name: registry-auth
      - mountPath: "/root/.ssh"
        name: ssh-key
  - name: minio
    image: quay.io/minio/minio:RELEASE.2023-01-12T02-06-16Z
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
    ports:
      - containerPort: 9000
        hostPort: 9000
        protocol: TCP
      - containerPort: 9090
        hostPort: 9090
        protocol: TCP
    volumeMounts:
    - mountPath: /data
      name: minio-data
  - name: registry
    image: docker.io/library/registry:2.8.1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 5000
        hostPort: 5000
        protocol: TCP
    env:
    - name: REGISTRY_AUTH
      value: "htpasswd"
    - name: REGISTRY_AUTH_HTPASSWD_REALM
      value: "Registry Realm"
    - name: REGISTRY_AUTH_HTPASSWD_PATH
      value: "/etc/containers/htpasswd"
    - name: REGISTRY_HTTP_TLS_CERTIFICATE
      value: "/etc/containers/certs.d/registry.kubespray.com:5000/registry.kubespray.com.crt"
    - name: REGISTRY_HTTP_TLS_KEY
      value: "/etc/containers/certs.d/registry.kubespray.com:5000/registry.kubespray.com.key"
    - name: REGISTRY_HTTP_RELATIVEURLS
      value: "true"
    - name: REGISTRY_HTTP_HOST
      value: "https://registry.kubespray.com:5000"
    - name: REGISTRY_HTTP_ADDR
      value: "0.0.0.0:5000"
    volumeMounts:
      - mountPath: "/registry"
        name: registry-data
      - mountPath: "/etc/containers"
        name: registry-auth
  volumes:
    - name: kubespray-data
      persistentVolumeClaim:
        claimName: kubespray-data-claim
    - name: registry-data
      persistentVolumeClaim:
        claimName: registry-data-claim
    - name: minio-data
      persistentVolumeClaim:
        claimName: minio-data-claim
    - name: ssh-key
      hostPath:
        path: /root/.ssh
        type: Directory
    - name: registry-auth
      emptyDir: {}
