apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-4-netdevice
  namespace: sriov-network-operator
spec:
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  resourceName: intelnics4
  priority: 99
  mtu: 9000
  numVfs: 8
  nicSelector:
    deviceID: "159b"
    rootDevices:
      - "0000:5e:00.1"
    vendor: "8086"
  deviceType: netdevice
