- name: install app
  block:
    - name: "addons | create kubernetes-apps dir"
      file:
        path: "{{ kube_config_dir }}/kubernetes-apps"
        state: directory
        mode: 0755

    - name:  download helm charts and Unarchive
      ansible.builtin.unarchive:
        src: "{{ files_repo }}/github.com/neuvector/neuvector-helm/archive/refs/tags/{{ app_chart_version }}.tar.gz"
        dest: "{{ kube_config_dir }}/kubernetes-apps"
        remote_src: yes

    - name: Kubernetes Apps | copy helm values file
      become: yes
      template:
        src: "{{ app_name }}.values.yaml.j2"
        dest: "{{ kube_config_dir }}//kubernetes-apps/{{ app_name }}.values.yaml"
        mode: 0644

    - name: 'addons | install {{ app_name }} helm charts'
      kubernetes.core.helm:
        name: '{{ app_name }}'
        chart_ref: "{{ kube_config_dir }}/kubernetes-apps/neuvector-helm-{{ app_chart_version }}/charts/core"
        release_namespace: '{{ app_name }}'
        create_namespace: true
        values_files: "{{ kube_config_dir }}//kubernetes-apps/{{ app_name }}.values.yaml"
  when:
    - uninstall is undefined
    - inventory_hostname == groups['kube_control_plane'][0]

- name: uninstall app
  block:
    - name: uninstall app
      kubernetes.core.helm:
        name: "{{ app_name }}"
        state: absent
        namespace: '{{ app_namespace }}'
  when:
    - uninstall is defined
    - inventory_hostname == groups['kube_control_plane'][0]
