- name: install app
  block:
    - name: "addons | create kubernetes-apps dir"
      file:
        path: "{{ kube_config_dir }}/kubernetes-apps"
        state: directory
        mode: 0755

    - name: 'addons | download helm charts'
      ansible.builtin.get_url:
        url: "{{ files_repo }}/github.com/k8snetworkplumbingwg/sriov-network-operator/releases/download/v{{ app_version }}/sriov-network-operator-{{ app_version }}.tgz"
        dest: "{{ kube_config_dir }}/kubernetes-apps"

    - name: Kubernetes Apps | copy helm values file
      become: yes
      template:
        src: "{{ app_name }}.values.yaml.j2"
        dest: "{{ kube_config_dir }}//kubernetes-apps/{{ app_name }}.values.yaml"
        mode: 0644

    - name: "addons | copy SriovOperatorConfig-patch.yaml files"
      copy:
        src: "{{ item }}"
        dest: "{{ kube_config_dir }}/kubernetes-apps"
        mode: 0755
      with_items:
        - SriovOperatorConfig-patch.yaml

    - name: 'addons | install {{ app_name }} helm charts'
      kubernetes.core.helm:
        name: '{{ app_name }}'
        chart_ref: "{{ kube_config_dir }}//kubernetes-apps/sriov-network-operator-{{ app_version }}.tgz"
        release_namespace: '{{ app_name }}'
        create_namespace: true
        values_files: "{{ kube_config_dir }}//kubernetes-apps/{{ app_name }}.values.yaml"

    - name: Set sriov label for node
      command: "{{ bin_dir }}/kubectl label nodes {{ inventory_hostname }} node-role.kubernetes.io/worker=sriov --overwrite=true"
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      changed_when: false

    - name: waiting operator
      shell: "{{ bin_dir }}/kubectl -n sriov-network-operator rollout status deployment.apps/sriov-network-operator"
      register: deploy_status
      until: deploy_status.stdout.find("successfully") != -1
      retries: 15
      delay: 15
      ignore_errors: true
      when:
        - inventory_hostname == groups['kube_control_plane'][0]

    - name: "addons | apply SriovOperatorConfig-patch.yaml"
      kube:
        state: latest
        kubectl: "{{ bin_dir }}/kubectl"
        filename: "{{ item }}"
        wait: yes
      with_items:
        - "{{ kube_config_dir }}/kubernetes-apps/SriovOperatorConfig-patch.yaml"

  when:
    - uninstall is undefined
    - inventory_hostname == groups['kube_control_plane'][0]

- name: uninstall app
  block:
    - name: uninstall sriov helm app
      kubernetes.core.helm:
        name: "{{ app_name }}"
        state: absent
        namespace: '{{ app_namespace }}'

    - name: uninstall sriov-network-config-daemon
      shell: "{{ bin_dir }}/kubectl -n sriov-network-operator delete daemonset.apps/sriov-network-config-daemon"

    - name: delete sriov namespace
      shell: "{{ bin_dir }}/kubectl -n sriov-network-operator delete ns sriov-network-operator"

  when:
    - uninstall is defined
    - inventory_hostname == groups['kube_control_plane'][0]

- include_tasks: sriov-policy.yaml
  when:
    - sriov_policy_enabled
