name: kubespray-playbook
on:
   workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  KUBESPRAY_VERSION: v2.21.0
  KUBERNETES_VERSION: v1.25.6
  PACKAGE_VERSION: v1.0
  CALICO_VERSION: v3.24.5
  CALICO_OPERATOR_VERSION: v1.28.5
  REGISTRY: registry.cn-shenzhen.aliyuncs.com/cnmirror
  DIST_PATH: ${{ github.workspace }}/kubespray-offline_${KUBERNETES_VERSION}_${PACKAGE_VERSION}
  IMAGES_LIST: kubespray/contrib/offline/temp/images.list

jobs:
  kubespray:
    runs-on: ubuntu-22.04     
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
        with:
          driver-opts: network=host
          
      - name: Login to Aliyun Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.playbook
          push: true
          tags: ${{ env.REGISTRY }}/kubespray:${{ env.KUBESPRAY_VERSION }}
          build-args: |
            KUBESPRAY_VERSION=${{ env.KUBESPRAY_VERSION }}
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
            PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
            CALICO_VERSION=${{ env.CALICO_VERSION }}
            CALICO_OPERATOR_VERSION=${{ env.CALICO_OPERATOR_VERSION }}
